name: Build and Deploy Mansite
# interactive shell

on:
  push:
    branches:
      - main # Change to your default branch if different

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git

      - name: Disable git "detached head" warning
        run: git config --global advice.detachedHead false

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Pause for debugging
      #   run: sleep infinity

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install npm packages
        run: npm ci

      - name: Build Middleman site and assets with mansite script
        run: ./mansite build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    # Add a dependency to the build job
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
