name: Build and Deploy Mansite

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git

      - name: Disable git "detached head" warning
        run: git config --global advice.detachedHead false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install npm packages
        run: npm ci

      - name: Build Middleman site and assets with mansite script
        run: ./mansite build

      - name: Get build directory path
        id: get-build-dir
        run: |
          echo "build_dir=$( grep '^prefix:' data/site.yml | sed -E 's/^prefix: //' )" >> $GITHUB_ENV

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/${{ env.build-dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
